import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 16.0

[font.bold]
family = "Monaspace Neon"
style = "Bold"

[font.bold_italic]
family = "Monaspace Radon"
style = "Bold Italic"

[font.italic]
family = "Monaspace Radon"
style = "Italic"

[font.normal]
family = "Monaspace Neon"
style = "Regular"
